name: Install Python Dependencies and Check for Conflicts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for Python dependency conflicts
        run: |
          pip check

      - name: Run tests
        run: |
          # Run your tests here
          echo "Running tests..."